services:
  media-server:
    build:
      context: ./ongaku_media_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADDRESS=0.0.0.0
      - PORT=8080

  apk-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL} # Change this to your public IP or domain for hosting
    volumes:
      - ./builds:/output