services:
  media-server:
    build:
      context: ./ongaku_media_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ADDRESS=0.0.0.0
      - PORT=8080

  apk-builder:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    args:
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./builds:/output