name: ongaku
description: "A music player"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.12
  flutter_riverpod: ^2.4.9
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.18
  flutter_webrtc: ^0.12.0
  flutter_foreground_task: ^6.1.2
  cached_network_image: ^3.3.0
  file_picker: ^8.3.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  dynamic_color: ^1.3.0
  google_fonts: ^5.0.0
  wakelock_plus: ^1.4.0
  intl: ^0.20.2
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true

  assets:
    - .env