name: ongaku_server
description: A server for handling file uploads and downloads for the Ongaku music app
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.2
  shelf_multipart: ^2.0.1
  path: ^1.8.3
  mime: ^1.0.4
  http: ^1.1.0
  http_parser: ^4.0.2
  dotenv: ^4.2.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.1

# The following line prevents the package from being accidentally published to
# pub.dev using `dart pub publish`. This is preferred for private packages.
publish_to: none
